SUPABASE_URL = "https://wjikdpjpmejtwrfhtelh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaWtkcGpwbWVqdHdyZmh0ZWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NDI5NjcsImV4cCI6MjA4MDIxODk2N30.k3H89yBbjR3OS-rt5exK6JT6G00PgBiE457kgC3_tqU"
ADMIN_PASSWORD = "123456"